version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: osrsuser
      POSTGRES_PASSWORD: osrspassword
      POSTGRES_DB: osrsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_USER: osrsuser
      POSTGRES_PASSWORD: osrspassword
      POSTGRES_DB: osrsdb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
