"""add lowalch highalch value to Item

Revision ID: 241f6e73cc0a
Revises: 57b6995ce21f
Create Date: 2025-06-15 15:07:12.703520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241f6e73cc0a'
down_revision: Union[str, None] = '57b6995ce21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('lowalch', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('highalch', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'value')
    op.drop_column('items', 'highalch')
    op.drop_column('items', 'lowalch')
    # ### end Alembic commands ###
